#!/usr/bin/env python3
"""Keep the SAST privacy regression inside the detector's real contract.

SEC-003 intentionally requires a quoted `sk-` literal. The privacy regression
must vary the secret's position *within valid quoted literal syntax*, not ask the
detector to recognize unrelated unquoted text. This changes only the test
fixture; the zero-source-byte redaction requirement remains strict.
"""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
PATH = ROOT / "entroly-engine/src/sast.rs"


def main() -> int:
    text = PATH.read_text(encoding="utf-8")
    old = '''        let cases = [
            format!("{secret} trailing diagnostic text"),
            format!("prefix text {secret} trailing text"),
            format!("prefix text ending with {secret}"),
            format!("{secret} = placeholder"),
        ];
'''
    new = '''        let cases = [
            format!("\\\"{secret}\\\" trailing diagnostic text"),
            format!("prefix text \\\"{secret}\\\" trailing text"),
            format!("prefix text ending with \\\"{secret}\\\""),
            format!("\\\"{secret}\\\" = placeholder"),
        ];
'''
    if new in text:
        print("SAST privacy fixture already aligned")
        return 0
    if text.count(old) != 1:
        raise SystemExit(
            "expected exactly one SAST privacy fixture generated by the hardening writer"
        )
    PATH.write_text(text.replace(old, new, 1), encoding="utf-8")
    print("aligned SAST privacy fixture with quoted SEC-003 literals")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
