"""
entroly.agent_skills — Generate Claude Agent Skills files from packed context.

Closes competitive gap vs Repomix: "Claude Skills generation built-in"

Reference: https://docs.anthropic.com/en/docs/agents/skills
"""
from __future__ import annotations

import json
import textwrap
from pathlib import Path
from typing import Any


# ---------------------------------------------------------------------------
# Skills file generation
# ---------------------------------------------------------------------------

SKILL_TEMPLATE = """\
---
name: {name}
description: {description}
version: "1.0"
author: generated-by-entroly
---

# {title}

{overview}

## Key Files

{file_list}

## Usage

```python
# Install: pip install entroly
from entroly import compress

context = compress(
    "{source}",
    query="your task description here",
)
# context is now optimised for the {name} codebase
```

## Capabilities

{capabilities}

## Notes

- Generated by [Entroly](https://github.com/juyterman1000/entroly)
- Compressed with reversible context reduction + Merkle receipt
- Re-generate with: `entroly go {source} --generate-skills`
"""


def generate_skills_file(
    source: str,
    files: list[dict[str, Any]],
    *,
    name: str | None = None,
    description: str | None = None,
    output_path: str | Path | None = None,
    top_k_files: int = 30,
) -> str:
    """
    Generate a Claude Agent Skills markdown file for a packed codebase.

    Parameters
    ----------
    source : str
        Source path or GitHub URL of the repository.
    files : list[dict]
        Packed file list (each with ``path`` and ``content``).
    name : str | None
        Skill name (defaults to the repo/directory name).
    description : str | None
        Short description for the skill.
    output_path : str | Path | None
        If given, write the skill file to this path.
    top_k_files : int
        Maximum number of files to list in the skills file.

    Returns
    -------
    str — the skills file content.
    """
    if not name:
        name = Path(source).name.replace(".git", "") or "codebase"

    if not description:
        description = f"AI context skill for the {name} codebase"

    # Detect capabilities from file extensions
    capabilities = _detect_capabilities(files)

    # File list (top_k, sorted by importance heuristic)
    important = _rank_files(files)[:top_k_files]
    file_lines = "\n".join(f"- `{f['path']}`" for f in important)

    # Overview
    lang_summary = ", ".join(sorted(set(_ext_to_lang(f["path"]) for f in files if _ext_to_lang(f["path"])))[:6])
    overview = (
        f"A context skill for **{name}**, covering {len(files)} files "
        f"written in {lang_summary or 'multiple languages'}. "
        f"Use this skill to ground AI agents with accurate, up-to-date codebase knowledge."
    )

    content = SKILL_TEMPLATE.format(
        name=name,
        title=f"{name} Codebase Skill",
        description=json.dumps(description),
        overview=overview,
        file_list=file_lines or "*(no files)*",
        source=source,
        capabilities="\n".join(f"- {c}" for c in capabilities),
    )

    if output_path:
        Path(output_path).write_text(content, encoding="utf-8")

    return content


def _detect_capabilities(files: list[dict]) -> list[str]:
    """Infer codebase capabilities from file types."""
    exts = {Path(f["path"]).suffix.lower() for f in files}
    caps: list[str] = []
    if ".py" in exts:
        caps.append("Python codebase understanding")
    if ".rs" in exts:
        caps.append("Rust codebase understanding")
    if {".ts", ".tsx", ".js", ".jsx"} & exts:
        caps.append("TypeScript/JavaScript codebase understanding")
    if ".go" in exts:
        caps.append("Go codebase understanding")
    if {".yaml", ".yml", ".toml"} & exts:
        caps.append("Configuration and infrastructure awareness")
    if ".md" in exts:
        caps.append("Documentation context")
    if {".sql"} & exts:
        caps.append("Database schema awareness")
    if not caps:
        caps.append("General codebase context")
    caps.append("Accurate file path citation")
    caps.append("Code pattern and convention awareness")
    return caps


def _rank_files(files: list[dict]) -> list[dict]:
    """Rank files by likely importance for AI context."""
    PRIORITY_NAMES = {
        "README.md", "readme.md", "README.rst",
        "AGENTS.md", "CLAUDE.md", "GEMINI.md",
        "pyproject.toml", "Cargo.toml", "package.json", "go.mod",
        "main.py", "main.rs", "main.ts", "index.ts", "index.js",
        "__init__.py", "lib.rs",
    }
    priority, rest = [], []
    for f in files:
        if Path(f["path"]).name in PRIORITY_NAMES:
            priority.append(f)
        else:
            rest.append(f)
    return priority + sorted(rest, key=lambda f: len(f.get("content", "")), reverse=True)


_EXT_LANG = {
    ".py": "Python", ".rs": "Rust", ".js": "JavaScript", ".ts": "TypeScript",
    ".tsx": "TypeScript", ".jsx": "JavaScript", ".go": "Go", ".java": "Java",
    ".rb": "Ruby", ".cpp": "C++", ".c": "C", ".cs": "C#", ".kt": "Kotlin",
    ".swift": "Swift", ".php": "PHP", ".r": "R", ".lua": "Lua",
    ".ex": "Elixir", ".sh": "Shell",
}


def _ext_to_lang(path: str) -> str:
    return _EXT_LANG.get(Path(path).suffix.lower(), "")


# ---------------------------------------------------------------------------
# Batch generation
# ---------------------------------------------------------------------------

def generate_skills_directory(
    source: str,
    files: list[dict[str, Any]],
    output_dir: str | Path = ".claude/skills",
    *,
    name: str | None = None,
) -> Path:
    """
    Write skill files into a directory tree compatible with Claude's skill loader.

    Returns the path to the main skill file.
    """
    output_dir = Path(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    skill_name = name or Path(source).name.replace(".git", "") or "codebase"
    skill_path = output_dir / f"{skill_name}.md"
    generate_skills_file(source, files, name=skill_name, output_path=skill_path)
    return skill_path
