"""Minimal self-hosted collector for consented product-health events.

The collector stores only the closed schema accepted by
``entroly.product_telemetry``. It never stores request IPs, headers, user-agent
strings, raw request bodies, or identifiers outside the monthly rotating
pseudonym generated by the client. Summary responses contain aggregates only.
"""

from __future__ import annotations

import argparse
import hmac
import json
import os
import re
import sqlite3
from collections import Counter, defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

from .product_telemetry import (
    BATCH_SCHEMA_VERSION,
    DELETE_SCHEMA_VERSION,
    MAX_BATCH_BYTES,
    MAX_BATCH_EVENTS,
    sanitize_public_event,
)


DEFAULT_COLLECTOR_RETENTION_DAYS = 90
_INSTALLATION_ID = re.compile(r"^[0-9a-f]{24}$")


def _retention_days() -> int:
    raw = os.environ.get("ENTROLY_TELEMETRY_COLLECTOR_RETENTION_DAYS", "90")
    try:
        return max(1, min(int(raw), 365))
    except ValueError:
        return DEFAULT_COLLECTOR_RETENTION_DAYS


def validate_batch_payload(value: Any) -> list[dict[str, Any]]:
    if not isinstance(value, dict) or set(value) != {"schema_version", "events"}:
        raise ValueError("batch must contain only schema_version and events")
    if value.get("schema_version") != BATCH_SCHEMA_VERSION:
        raise ValueError("unsupported telemetry batch schema")
    events = value.get("events")
    if not isinstance(events, list) or not 1 <= len(events) <= MAX_BATCH_EVENTS:
        raise ValueError(f"events must contain 1..{MAX_BATCH_EVENTS} items")
    validated: list[dict[str, Any]] = []
    today = datetime.now(timezone.utc).date()
    oldest = today - timedelta(days=_retention_days())
    newest = today + timedelta(days=1)
    for event in events:
        clean = sanitize_public_event(event, strict=True)
        if clean is None:
            raise ValueError("event does not match the closed telemetry schema")
        occurred_on = datetime.fromisoformat(clean["occurred_on"]).date()
        if not oldest <= occurred_on <= newest:
            raise ValueError("event day is outside the collector retention window")
        validated.append(clean)
    return validated


def validate_deletion_payload(value: Any) -> list[str]:
    if not isinstance(value, dict) or set(value) != {
        "schema_version", "installation_ids",
    }:
        raise ValueError("deletion must contain only schema_version and installation_ids")
    if value.get("schema_version") != DELETE_SCHEMA_VERSION:
        raise ValueError("unsupported telemetry deletion schema")
    installation_ids = value.get("installation_ids")
    if not isinstance(installation_ids, list) or not 1 <= len(installation_ids) <= 4:
        raise ValueError("installation_ids must contain 1..4 monthly pseudonyms")
    if any(
        not isinstance(item, str) or not _INSTALLATION_ID.fullmatch(item)
        for item in installation_ids
    ):
        raise ValueError("invalid monthly pseudonym")
    return list(dict.fromkeys(installation_ids))


class TelemetryStore:
    """SQLite event sink with retention and aggregate-only reporting."""

    def __init__(self, path: str | Path):
        self.path = Path(path)
        self.path.parent.mkdir(parents=True, exist_ok=True)
        with self._connect() as connection:
            connection.executescript(
                """
                PRAGMA journal_mode=WAL;
                PRAGMA synchronous=FULL;
                CREATE TABLE IF NOT EXISTS product_events (
                    event_id TEXT PRIMARY KEY,
                    occurred_on TEXT NOT NULL,
                    installation_id TEXT NOT NULL,
                    event_name TEXT NOT NULL,
                    version TEXT NOT NULL,
                    platform TEXT NOT NULL,
                    python TEXT NOT NULL,
                    properties_json TEXT NOT NULL
                );
                CREATE INDEX IF NOT EXISTS idx_product_events_day
                    ON product_events(occurred_on);
                CREATE INDEX IF NOT EXISTS idx_product_events_name_day
                    ON product_events(event_name, occurred_on);
                """
            )
            self._prune(connection)

    def _connect(self) -> sqlite3.Connection:
        connection = sqlite3.connect(self.path, timeout=5.0)
        connection.execute("PRAGMA busy_timeout=5000")
        return connection

    @staticmethod
    def _prune(connection: sqlite3.Connection) -> None:
        cutoff = (
            datetime.now(timezone.utc).date() - timedelta(days=_retention_days())
        ).isoformat()
        connection.execute(
            "DELETE FROM product_events WHERE occurred_on < ?",
            (cutoff,),
        )

    def ingest(self, events: list[dict[str, Any]]) -> int:
        inserted = 0
        with self._connect() as connection:
            self._prune(connection)
            for event in events:
                cursor = connection.execute(
                    """
                    INSERT OR IGNORE INTO product_events (
                        event_id, occurred_on, installation_id, event_name,
                        version, platform, python, properties_json
                    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
                    """,
                    (
                        event["event_id"],
                        event["occurred_on"],
                        event["installation_id"],
                        event["event_name"],
                        event["version"],
                        event["platform"],
                        event["python"],
                        json.dumps(event["properties"], sort_keys=True, separators=(",", ":")),
                    ),
                )
                inserted += max(0, int(cursor.rowcount))
        return inserted

    def delete_installations(self, installation_ids: list[str]) -> int:
        padded = (installation_ids + [""] * 4)[:4]
        with self._connect() as connection:
            cursor = connection.execute(
                "DELETE FROM product_events WHERE installation_id IN (?, ?, ?, ?)",
                tuple(padded),
            )
        return max(0, int(cursor.rowcount))

    def summary(self, *, days: int = 30) -> dict[str, Any]:
        bounded_days = max(1, min(int(days), _retention_days()))
        since = (
            datetime.now(timezone.utc).date() - timedelta(days=bounded_days - 1)
        ).isoformat()
        with self._connect() as connection:
            rows = connection.execute(
                """
                SELECT occurred_on, installation_id, event_name, version,
                       platform, python, properties_json
                  FROM product_events
                 WHERE occurred_on >= ?
                """,
                (since,),
            ).fetchall()

        active_ids: set[str] = set()
        activated_ids: set[str] = set()
        benefited_ids: set[str] = set()
        provider_bound_benefited_ids: set[str] = set()
        modeled_cost_ids: set[str] = set()
        event_counts: Counter[str] = Counter()
        command_counts: Counter[str] = Counter()
        command_errors: Counter[str] = Counter()
        error_types: Counter[str] = Counter()
        surfaces: Counter[str] = Counter()
        versions: Counter[str] = Counter()
        token_savings_buckets: Counter[str] = Counter()
        reduction_percent_buckets: Counter[str] = Counter()
        measurement_scopes: Counter[str] = Counter()
        cost_evidence: Counter[str] = Counter()
        platform_active_ids: dict[str, set[str]] = defaultdict(set)
        platform_benefited_ids: dict[str, set[str]] = defaultdict(set)
        platform_events: Counter[str] = Counter()
        platform_command_attempts: Counter[str] = Counter()
        platform_command_failures: Counter[str] = Counter()
        command_successes = 0
        command_failures = 0
        optimization_observations = 0
        positive_optimization_observations = 0

        for _day, installation_id, event_name, version, platform_name, _python, raw in rows:
            installation = str(installation_id)
            platform_key = str(platform_name)
            active_ids.add(installation)
            platform_active_ids[platform_key].add(installation)
            platform_events[platform_key] += 1
            event_counts[str(event_name)] += 1
            versions[str(version)] += 1
            try:
                properties = json.loads(raw)
            except (json.JSONDecodeError, TypeError):
                properties = {}
            if event_name == "activation":
                activated_ids.add(installation)
            if event_name in {"surface_started", "surface_error"}:
                surfaces[str(properties.get("surface", "other"))] += 1
            if event_name == "surface_error":
                error_types[str(properties.get("error_type", "OtherError"))] += 1
            if event_name == "command":
                command = str(properties.get("command", "other"))
                result = str(properties.get("result", "error"))
                command_counts[command] += 1
                platform_command_attempts[platform_key] += 1
                if result == "success":
                    command_successes += 1
                elif result == "error":
                    command_failures += 1
                    platform_command_failures[platform_key] += 1
                    command_errors[command] += 1
                    error_types[str(properties.get("error_type", "OtherError"))] += 1
            if event_name == "optimization_outcome":
                optimization_observations += 1
                token_bucket = str(properties.get("tokens_saved_bucket", "none"))
                reduction_bucket = str(
                    properties.get("reduction_percent_bucket", "none")
                )
                scope = str(properties.get("measurement_scope", "local_estimate"))
                cost_signal = str(properties.get("cost_evidence", "not_available"))
                token_savings_buckets[token_bucket] += 1
                reduction_percent_buckets[reduction_bucket] += 1
                measurement_scopes[scope] += 1
                cost_evidence[cost_signal] += 1
                if token_bucket != "none":
                    positive_optimization_observations += 1
                    benefited_ids.add(installation)
                    platform_benefited_ids[platform_key].add(installation)
                    if scope == "provider_bound_estimate":
                        provider_bound_benefited_ids.add(installation)
                    if cost_signal == "modeled_positive":
                        modeled_cost_ids.add(installation)

        attempted = command_successes + command_failures
        error_rate = round(command_failures / attempted, 6) if attempted else None
        observed_benefit_rate = (
            round(len(benefited_ids) / len(active_ids), 6) if active_ids else None
        )
        platforms: dict[str, dict[str, Any]] = {}
        for platform_name in sorted(platform_active_ids):
            platform_attempted = platform_command_attempts[platform_name]
            platform_failed = platform_command_failures[platform_name]
            platforms[platform_name] = {
                "active_monthly_pseudonyms": len(platform_active_ids[platform_name]),
                "events": platform_events[platform_name],
                "command_observations": platform_attempted,
                "failed_command_observations": platform_failed,
                "observed_command_error_rate": (
                    round(platform_failed / platform_attempted, 6)
                    if platform_attempted
                    else None
                ),
                "benefited_monthly_pseudonyms": len(
                    platform_benefited_ids[platform_name]
                ),
            }
        return {
            "schema_version": "entroly.product-telemetry-summary.v1",
            "window_days": bounded_days,
            "since": since,
            "privacy": {
                "identifier": "monthly rotating pseudonym",
                "unique_user_claim_allowed": False,
                "ip_or_headers_stored": False,
                "raw_events_returned": False,
                "exact_tokens_or_costs_stored": False,
                "model_identifiers_stored": False,
                "usage_volume_claim_allowed": False,
            },
            "active_monthly_pseudonyms": len(active_ids),
            "activation_monthly_pseudonyms": len(activated_ids),
            "events": dict(sorted(event_counts.items())),
            "commands": {
                "observations": attempted,
                "successful_observations": command_successes,
                "failed_observations": command_failures,
                "observed_error_rate": error_rate,
                "observations_by_command": dict(sorted(command_counts.items())),
                "error_observations_by_command": dict(sorted(command_errors.items())),
                "note": "Daily category observations are not command usage volume.",
            },
            "benefit": {
                "observations": optimization_observations,
                "positive_observations": positive_optimization_observations,
                "monthly_pseudonyms_with_positive_reduction": len(benefited_ids),
                "provider_bound_monthly_pseudonyms_with_positive_reduction": len(
                    provider_bound_benefited_ids
                ),
                "monthly_pseudonyms_with_modeled_cost_reduction": len(
                    modeled_cost_ids
                ),
                "observed_benefit_rate_among_active_pseudonyms": observed_benefit_rate,
                "token_savings_buckets": dict(sorted(token_savings_buckets.items())),
                "reduction_percent_buckets": dict(
                    sorted(reduction_percent_buckets.items())
                ),
                "measurement_scopes": dict(sorted(measurement_scopes.items())),
                "cost_evidence": dict(sorted(cost_evidence.items())),
                "money_savings_verified": False,
                "note": (
                    "Modeled cost reduction is derived from provider-bound token "
                    "reduction and configured rates; it is not a provider invoice."
                ),
            },
            "error_types": dict(sorted(error_types.items())),
            "platforms": platforms,
            "surfaces": dict(sorted(surfaces.items())),
            "versions": dict(sorted(versions.items())),
        }


def _authorized(request: Any, token: str) -> bool:
    if not token:
        return True
    supplied = str(request.headers.get("authorization", ""))
    return hmac.compare_digest(supplied, f"Bearer {token}")


def create_app(
    *,
    db_path: str | Path,
    ingest_token: str = "",
    admin_token: str = "",
) -> Any:
    """Build a loopback-friendly Starlette collector application."""
    from starlette.applications import Starlette
    from starlette.requests import Request
    from starlette.responses import JSONResponse
    from starlette.routing import Route

    store = TelemetryStore(db_path)

    async def health(_request: Request) -> JSONResponse:
        return JSONResponse({"status": "ok"})

    async def ingest(request: Request) -> JSONResponse:
        if not _authorized(request, ingest_token):
            return JSONResponse({"error": "unauthorized"}, status_code=401)
        raw = await request.body()
        if len(raw) > MAX_BATCH_BYTES:
            return JSONResponse({"error": "payload_too_large"}, status_code=413)
        try:
            payload = json.loads(raw)
            events = validate_batch_payload(payload)
        except (json.JSONDecodeError, UnicodeDecodeError, ValueError):
            return JSONResponse({"error": "invalid_schema"}, status_code=400)
        inserted = store.ingest(events)
        return JSONResponse({"accepted": len(events), "inserted": inserted})

    async def delete_events(request: Request) -> JSONResponse:
        if not _authorized(request, ingest_token):
            return JSONResponse({"error": "unauthorized"}, status_code=401)
        raw = await request.body()
        if len(raw) > 4096:
            return JSONResponse({"error": "payload_too_large"}, status_code=413)
        try:
            payload = json.loads(raw)
            installation_ids = validate_deletion_payload(payload)
        except (json.JSONDecodeError, UnicodeDecodeError, ValueError):
            return JSONResponse({"error": "invalid_schema"}, status_code=400)
        deleted = store.delete_installations(installation_ids)
        return JSONResponse({"deleted": deleted})

    async def summary(request: Request) -> JSONResponse:
        if not admin_token or not _authorized(request, admin_token):
            return JSONResponse({"error": "not_found"}, status_code=404)
        try:
            days = int(request.query_params.get("days", "30"))
        except ValueError:
            return JSONResponse({"error": "invalid_days"}, status_code=400)
        return JSONResponse(store.summary(days=days))

    return Starlette(
        routes=[
            Route("/health", health, methods=["GET"]),
            Route("/v1/events", ingest, methods=["POST"]),
            Route("/v1/events", delete_events, methods=["DELETE"]),
            Route("/v1/summary", summary, methods=["GET"]),
        ]
    )


def main() -> None:
    parser = argparse.ArgumentParser(description="Run the Entroly product telemetry collector")
    parser.add_argument("--db", type=Path, required=True)
    parser.add_argument("--host", default="127.0.0.1")
    parser.add_argument("--port", type=int, default=9381)
    args = parser.parse_args()
    if args.host not in {"127.0.0.1", "::1", "localhost"}:
        raise SystemExit(
            "collector binds loopback only; place an authenticated HTTPS reverse proxy in front"
        )
    if not 1 <= args.port <= 65535:
        raise SystemExit("--port must be between 1 and 65535")
    try:
        import uvicorn
    except ImportError:
        raise SystemExit("uvicorn is required to run the collector") from None
    app = create_app(
        db_path=args.db,
        ingest_token=os.environ.get("ENTROLY_TELEMETRY_INGEST_TOKEN", ""),
        admin_token=os.environ.get("ENTROLY_TELEMETRY_ADMIN_TOKEN", ""),
    )
    uvicorn.run(app, host=args.host, port=args.port, access_log=False)


if __name__ == "__main__":
    main()


__all__ = [
    "TelemetryStore",
    "create_app",
    "main",
    "validate_batch_payload",
    "validate_deletion_payload",
]
